import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CartProvider } from './context/CartContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TechNest-Ecommerce',
  description: 'Generated by create next app',
  icons: {
    icon:'../public/favicon.png'  
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
                 <div>{children}</div> 
        </CartProvider>
      </body>
    </html>
  )
}